name: Update Stock Data

on:
  schedule:
    - cron: "30 2 * * *"
  workflow_dispatch: # Allow manual trigger

jobs:
  back_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' #install the python needed
      - name: install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install yfinance
      - name: download stock data
        run: |
          python3 ./src/data/download_stocks.py

      - name: Commit and push if changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add --all
          if ! git diff --quiet && git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Update stocks data [automated]"
          git push
